"""
Disclaimer Template Tool for generating standardized legal notices and disclaimers.

This tool provides pre-approved disclaimer templates that comply with financial
regulatory requirements and AI disclosure standards.
"""

from typing import Dict, Any, List, Optional
from enum import Enum
from ...utils import setup_logger

logger = setup_logger(__name__)


class DisclaimerType(Enum):
    """Types of disclaimers available."""
    AI_DISCLOSURE = "ai_disclosure"
    GENERAL_FINANCIAL = "general_financial"
    INVESTMENT_RISK = "investment_risk"
    TAX_LIMITATION = "tax_limitation"
    LEGAL_LIMITATION = "legal_limitation"
    DATA_TIMELINESS = "data_timeliness"
    PAST_PERFORMANCE = "past_performance"
    NOT_FDIC_INSURED = "not_fdic_insured"
    NO_GUARANTEES = "no_guarantees"
    SUITABILITY_WARNING = "suitability_warning"
    PROFESSIONAL_CONSULTATION = "professional_consultation"
    REGULATORY_COMPLIANCE = "regulatory_compliance"


class DisclaimerTemplateTool:
    """
    Tool for generating standardized, compliant disclaimer text.

    Provides pre-approved disclaimer templates for various scenarios in
    financial advisory responses, ensuring consistent compliance with
    legal and regulatory requirements.
    """

    # Comprehensive disclaimer templates
    TEMPLATES = {
        DisclaimerType.AI_DISCLOSURE: {
            "title": "AI-Generated Advisory Notice",
            "template": """⚠️ **AI-GENERATED ADVISORY NOTICE**

This response was generated by an AI-powered financial advisory system using probabilistic Agentic AI technology. While we strive for accuracy, AI systems can make mistakes, provide incomplete information, or present outdated data. This information should not be considered as a substitute for professional financial advice from a licensed financial advisor. Always verify critical information independently and consult qualified professionals before making financial decisions.""",
            "severity": "MANDATORY",
            "applies_to": ["all"]
        },

        DisclaimerType.GENERAL_FINANCIAL: {
            "title": "General Financial Disclaimer",
            "template": """**DISCLAIMER:** This information is for educational and informational purposes only and does not constitute financial, investment, tax, or legal advice. Past performance does not guarantee future results. All investments carry risk, including potential loss of principal. Before making any financial decisions, please consult with a qualified financial advisor who can assess your specific situation.""",
            "severity": "MANDATORY",
            "applies_to": ["all", "investment_advice", "general_info", "market_analysis"]
        },

        DisclaimerType.INVESTMENT_RISK: {
            "title": "Investment Risk Disclaimer",
            "template": """**INVESTMENT RISK DISCLAIMER:** Investing involves risk, including the potential loss of principal. Securities and investment products are:
• Not FDIC insured
• Not bank guaranteed
• May lose value

Market volatility can significantly impact investment values. Diversification does not ensure a profit or protect against loss in declining markets. Consider your investment objectives, risk tolerance, time horizon, and financial circumstances before investing. Different types of investments involve varying degrees of risk, and there can be no assurance that any specific investment will be profitable.""",
            "severity": "MANDATORY",
            "applies_to": ["investment_advice", "product_explanation"]
        },

        DisclaimerType.TAX_LIMITATION: {
            "title": "Tax Advice Limitation",
            "template": """**TAX ADVISORY LIMITATION:** This system does not provide tax advice. Tax situations are highly individual and depend on numerous factors including your income, filing status, deductions, credits, and state/local regulations. Tax laws change frequently and can have significant financial implications. Please consult a qualified tax professional, Certified Public Accountant (CPA), or enrolled agent for advice specific to your tax situation.""",
            "severity": "MANDATORY",
            "applies_to": ["tax_advice"]
        },

        DisclaimerType.LEGAL_LIMITATION: {
            "title": "Legal Advice Limitation",
            "template": """**LEGAL ADVISORY LIMITATION:** This system does not provide legal advice. For legal matters related to financial planning, estate planning, trusts, contracts, or any other legal concerns, please consult a licensed attorney in your jurisdiction. Laws vary by state and change over time, and legal matters require professional legal counsel.""",
            "severity": "MANDATORY",
            "applies_to": ["legal_advice"]
        },

        DisclaimerType.DATA_TIMELINESS: {
            "title": "Data Currency Notice",
            "template": """**DATA CURRENCY NOTICE:** Financial data, market information, interest rates, and economic indicators presented may not reflect real-time conditions. Markets are dynamic and information can become outdated quickly. Always verify current prices, rates, terms, and market conditions through official sources or your financial institution before making financial decisions.""",
            "severity": "RECOMMENDED",
            "applies_to": ["market_analysis", "product_explanation", "investment_advice"]
        },

        DisclaimerType.PAST_PERFORMANCE: {
            "title": "Past Performance Warning",
            "template": """**PAST PERFORMANCE WARNING:** Past performance is not indicative of future results. Historical returns, yields, or performance data should not be assumed to represent future performance. Investment returns will fluctuate and are subject to market volatility, so that an investor's shares, when redeemed, may be worth more or less than their original cost.""",
            "severity": "MANDATORY",
            "applies_to": ["investment_advice", "market_analysis", "product_explanation"]
        },

        DisclaimerType.NOT_FDIC_INSURED: {
            "title": "FDIC Insurance Notice",
            "template": """**IMPORTANT:** Investment products mentioned are not FDIC insured, are not deposits or obligations of, or guaranteed by, any financial institution, and involve investment risks including possible loss of principal.""",
            "severity": "RECOMMENDED",
            "applies_to": ["investment_advice", "product_explanation"]
        },

        DisclaimerType.NO_GUARANTEES: {
            "title": "No Guarantees Notice",
            "template": """**NO GUARANTEES:** No investment strategy or risk management technique can guarantee returns or eliminate risk in all market environments. All investments contain risk and may lose value.""",
            "severity": "RECOMMENDED",
            "applies_to": ["investment_advice", "market_analysis"]
        },

        DisclaimerType.SUITABILITY_WARNING: {
            "title": "Suitability Assessment Notice",
            "template": """**SUITABILITY NOTICE:** Investment recommendations and strategies must be evaluated based on your individual circumstances, including:
• Financial situation and needs
• Investment objectives
• Risk tolerance
• Time horizon
• Tax situation
• Existing investments and overall portfolio

A one-size-fits-all approach to investing is inappropriate. Please consult with a financial advisor to determine what's suitable for your specific situation.""",
            "severity": "MANDATORY",
            "applies_to": ["investment_advice"]
        },

        DisclaimerType.PROFESSIONAL_CONSULTATION: {
            "title": "Professional Consultation Recommendation",
            "template": """**PROFESSIONAL CONSULTATION RECOMMENDED:** Before making significant financial decisions, we strongly recommend consulting with qualified professionals, including:
• Licensed Financial Advisors or Certified Financial Planners (CFP)
• Certified Public Accountants (CPA) for tax matters
• Licensed Attorneys for legal and estate planning matters
• Insurance professionals for insurance needs

These professionals can provide personalized advice based on a comprehensive understanding of your unique situation.""",
            "severity": "RECOMMENDED",
            "applies_to": ["all"]
        },

        DisclaimerType.REGULATORY_COMPLIANCE: {
            "title": "Regulatory Compliance Notice",
            "template": """**REGULATORY COMPLIANCE NOTICE:** This information is provided for general educational purposes and should not be construed as a recommendation to buy or sell any specific security or investment product. All investments are subject to federal and state securities laws and regulations. This system is not registered as an investment advisor under the Investment Advisers Act of 1940 or with any state securities commission.""",
            "severity": "RECOMMENDED",
            "applies_to": ["investment_advice", "product_explanation"]
        },
    }

    def get_tool_definition(self) -> Dict[str, Any]:
        """Return tool definition for agent integration."""
        return {
            "name": "generate_disclaimer",
            "description": (
                "Generates standardized, compliant disclaimer text for financial advisory responses. "
                "Provides pre-approved disclaimer templates based on content type and specific requirements. "
                "Ensures consistent legal compliance across all responses. Use this tool to add appropriate "
                "disclaimers when validating financial advisory content."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "content_type": {
                        "type": "string",
                        "description": "Type of financial content requiring disclaimers",
                        "enum": ["all", "investment_advice", "general_info", "product_explanation",
                                "market_analysis", "tax_advice", "legal_advice"]
                    },
                    "specific_disclaimers": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Specific disclaimer types to include. Options: ai_disclosure, general_financial, investment_risk, tax_limitation, legal_limitation, data_timeliness, past_performance, not_fdic_insured, no_guarantees, suitability_warning, professional_consultation, regulatory_compliance"
                    },
                    "include_all_mandatory": {
                        "type": "boolean",
                        "description": "If true, includes all mandatory disclaimers for the content type (default: true)",
                        "default": True
                    },
                    "format": {
                        "type": "string",
                        "description": "Output format: 'full' (complete text), 'compact' (abbreviated), 'list' (structured list)",
                        "enum": ["full", "compact", "list"],
                        "default": "full"
                    }
                },
                "required": ["content_type"]
            },
            "handler": self.generate_disclaimers
        }

    def generate_disclaimers(
        self,
        content_type: str,
        specific_disclaimers: Optional[List[str]] = None,
        include_all_mandatory: bool = True,
        format: str = "full"
    ) -> Dict[str, Any]:
        """
        Generate appropriate disclaimers based on content type.

        Args:
            content_type: Type of financial content
            specific_disclaimers: Specific disclaimers to include
            include_all_mandatory: Include all mandatory disclaimers for content type
            format: Output format (full, compact, list)

        Returns:
            Dictionary containing generated disclaimers and metadata
        """
        try:
            logger.info(f"Generating disclaimers for content_type: {content_type}")

            disclaimers_to_include = []
            mandatory_disclaimers = []
            recommended_disclaimers = []

            # Determine which disclaimers to include
            if include_all_mandatory:
                # Include AI disclosure (always mandatory)
                disclaimers_to_include.append(DisclaimerType.AI_DISCLOSURE)
                mandatory_disclaimers.append("ai_disclosure")

                # Add content-type specific mandatory disclaimers
                for disclaimer_type, details in self.TEMPLATES.items():
                    if (details["severity"] == "MANDATORY" and
                        (content_type in details["applies_to"] or "all" in details["applies_to"])):
                        if disclaimer_type not in disclaimers_to_include:
                            disclaimers_to_include.append(disclaimer_type)
                            mandatory_disclaimers.append(disclaimer_type.value)

            # Add specific requested disclaimers
            if specific_disclaimers:
                for disc_name in specific_disclaimers:
                    try:
                        disc_type = DisclaimerType(disc_name)
                        if disc_type not in disclaimers_to_include:
                            disclaimers_to_include.append(disc_type)
                            if self.TEMPLATES[disc_type]["severity"] == "RECOMMENDED":
                                recommended_disclaimers.append(disc_name)
                    except ValueError:
                        logger.warning(f"Unknown disclaimer type requested: {disc_name}")

            # Add recommended disclaimers for content type
            for disclaimer_type, details in self.TEMPLATES.items():
                if (details["severity"] == "RECOMMENDED" and
                    (content_type in details["applies_to"] or "all" in details["applies_to"]) and
                    disclaimer_type not in disclaimers_to_include):
                    recommended_disclaimers.append(disclaimer_type.value)

            # Generate output based on format
            if format == "full":
                output = self._generate_full_format(disclaimers_to_include)
            elif format == "compact":
                output = self._generate_compact_format(disclaimers_to_include)
            else:  # list
                output = self._generate_list_format(disclaimers_to_include)

            result = {
                "success": True,
                "content_type": content_type,
                "disclaimers_included": [dt.value for dt in disclaimers_to_include],
                "mandatory_included": mandatory_disclaimers,
                "recommended_available": recommended_disclaimers,
                "total_disclaimers": len(disclaimers_to_include),
                "formatted_output": output,
                "usage_instructions": (
                    "Add the formatted disclaimers to the beginning or end of the financial "
                    "advisory response. For best compliance, place AI disclosure at the top "
                    "and other disclaimers at the bottom."
                )
            }

            logger.info(f"Successfully generated {len(disclaimers_to_include)} disclaimers")
            return result

        except Exception as e:
            logger.error(f"Error generating disclaimers: {str(e)}")
            return {
                "success": False,
                "error": str(e),
                "fallback_disclaimer": self.TEMPLATES[DisclaimerType.AI_DISCLOSURE]["template"]
            }

    def _generate_full_format(self, disclaimer_types: List[DisclaimerType]) -> str:
        """Generate full-text disclaimer format."""
        sections = []

        for disclaimer_type in disclaimer_types:
            template_data = self.TEMPLATES[disclaimer_type]
            sections.append(template_data["template"])

        return "\n\n---\n\n".join(sections)

    def _generate_compact_format(self, disclaimer_types: List[DisclaimerType]) -> str:
        """Generate compact disclaimer format."""
        lines = []

        for disclaimer_type in disclaimer_types:
            template_data = self.TEMPLATES[disclaimer_type]
            # Extract first sentence or key message
            template_text = template_data["template"]
            # Remove markdown formatting for compact version
            clean_text = template_text.replace("**", "").replace("⚠️", "")
            # Take first substantial sentence
            first_line = clean_text.split("\n")[0]
            lines.append(f"• {first_line.strip()}")

        return "\n".join(lines)

    def _generate_list_format(self, disclaimer_types: List[DisclaimerType]) -> List[Dict[str, str]]:
        """Generate structured list format."""
        result = []

        for disclaimer_type in disclaimer_types:
            template_data = self.TEMPLATES[disclaimer_type]
            result.append({
                "type": disclaimer_type.value,
                "title": template_data["title"],
                "text": template_data["template"],
                "severity": template_data["severity"],
                "applies_to": template_data["applies_to"]
            })

        return result

    def get_available_disclaimers(self) -> List[Dict[str, str]]:
        """Get list of all available disclaimer types."""
        return [
            {
                "type": dt.value,
                "title": self.TEMPLATES[dt]["title"],
                "severity": self.TEMPLATES[dt]["severity"],
                "applies_to": self.TEMPLATES[dt]["applies_to"]
            }
            for dt in DisclaimerType
        ]


# Create singleton instance
disclaimer_template_tool = DisclaimerTemplateTool()


# Export the tool definition function for agent integration
def get_disclaimer_template_tool():
    """Get the disclaimer template tool for agent integration."""
    return disclaimer_template_tool.get_tool_definition()
