"""
Test script for the Compliance Checker Agent in isolation.

This script tests the compliance checker agent's ability to:
1. Validate financial advisory responses
2. Detect prohibited content (guarantees, misleading statements)
3. Check for required disclaimers
4. Generate appropriate disclaimers
5. Assess compliance status (APPROVED, REQUIRES_MODIFICATION, REJECTED)
"""

import asyncio
import sys
from pathlib import Path

# Add parent directory to path
sys.path.append(str(Path(__file__).parent))

from financial_advisor_agent.sub_agents.compliance_checker_agent.agent import compliance_checker_agent
from financial_advisor_agent.utils import setup_logger

logger = setup_logger(__name__)


# Test cases with different compliance scenarios
TEST_CASES = [
    {
        "name": "Non-Compliant - Guaranteed Returns",
        "response": """
        You should invest in this mutual fund because it has guaranteed returns of 12% per year.
        This is a risk-free investment that will definitely make you money. Past performance shows
        consistent gains, so you can't lose with this one!
        """,
        "expected_status": "REJECTED"
    },

    {
        "name": "Non-Compliant - Missing AI Disclosure",
        "response": """
        Based on your investment goals and risk tolerance, diversified index funds could be
        a suitable option for long-term growth. These funds offer exposure to a broad market
        and have historically provided steady returns over time.

        DISCLAIMER: This information is for educational purposes only. Please consult a
        financial advisor before making investment decisions.
        """,
        "expected_status": "REQUIRES_MODIFICATION"
    },

    {
        "name": "Partially Compliant - Missing Risk Disclosure",
        "response": """
        ⚠️ AI-GENERATED ADVISORY NOTICE
        This response was generated by an AI-powered financial advisory system using
        probabilistic Agentic AI technology. AI systems can make mistakes. Please consult
        a licensed financial advisor before making decisions.

        Based on your goals, you might consider a diversified portfolio of stocks and bonds.

        DISCLAIMER: This is for educational purposes only and does not constitute
        financial advice.
        """,
        "expected_status": "REQUIRES_MODIFICATION"
    },

    {
        "name": "Fully Compliant Response",
        "response": """
        ⚠️ AI-GENERATED ADVISORY NOTICE
        This response was generated by an AI-powered financial advisory system using probabilistic
        Agentic AI technology. While we strive for accuracy, AI systems can make mistakes, provide
        incomplete information, or present outdated data. This information should not be considered
        as a substitute for professional financial advice from a licensed financial advisor. Always
        verify critical information independently and consult qualified professionals before making
        financial decisions.

        Based on your investment objectives, risk tolerance, and time horizon, you might consider
        a diversified portfolio approach including:

        - Index funds for broad market exposure
        - Bond allocation based on your risk tolerance
        - Regular rebalancing to maintain target allocation

        INVESTMENT RISK DISCLAIMER: Investing involves risk, including the potential loss of
        principal. Market volatility can significantly impact investment values. Securities are
        not FDIC insured and may lose value. Past performance does not guarantee future results.
        Diversification does not ensure profit or protect against loss.

        DISCLAIMER: This information is for educational and informational purposes only and
        does not constitute financial, investment, tax, or legal advice. Please consult with a
        qualified financial advisor, CPA, or attorney before making financial decisions.
        """,
        "expected_status": "APPROVED"
    },

    {
        "name": "Tax Advice - Should Require Tax Professional Disclaimer",
        "response": """
        Regarding tax-loss harvesting, this strategy involves selling investments at a loss
        to offset capital gains. It can be an effective way to reduce your tax burden.
        """,
        "expected_status": "REQUIRES_MODIFICATION or REJECTED"
    }
]


async def test_compliance_validation_tool():
    """Test the compliance validation tool directly."""
    logger.info("\n" + "="*80)
    logger.info("TESTING COMPLIANCE VALIDATION TOOL")
    logger.info("="*80 + "\n")

    # Get the compliance checklist tool
    from financial_advisor_agent.sub_agents.compliance_checker_agent.compliance_checklist_tool import compliance_checklist_tool

    for i, test_case in enumerate(TEST_CASES, 1):
        logger.info(f"\n{'='*80}")
        logger.info(f"Test Case {i}: {test_case['name']}")
        logger.info(f"Expected: {test_case['expected_status']}")
        logger.info(f"{'='*80}\n")

        # Determine response type based on test case
        response_type = "investment_advice"
        if "tax" in test_case['name'].lower():
            response_type = "tax_advice"

        # Validate compliance
        result = compliance_checklist_tool.validate_compliance(
            response_text=test_case['response'],
            response_type=response_type,
            strict_mode=True
        )

        # Display results
        logger.info(f"📊 Overall Status: {result['overall_status']}")
        logger.info(f"\n🔍 Checks Performed:")

        # AI Disclosure Check
        ai_check = result['checks_performed'].get('ai_disclosure', {})
        logger.info(f"  • AI Disclosure: {'✅ PASS' if ai_check.get('passed') else '❌ FAIL'}")
        if not ai_check.get('passed'):
            for issue in ai_check.get('issues', []):
                logger.info(f"    - [{issue['severity']}] {issue['issue']}")

        # Prohibited Content Check
        prohibited_check = result['checks_performed'].get('prohibited_content', {})
        logger.info(f"  • Prohibited Content: {'✅ PASS' if prohibited_check.get('passed') else '❌ FAIL'}")
        if not prohibited_check.get('passed'):
            for issue in prohibited_check.get('issues', []):
                logger.info(f"    - [{issue['severity']}] {issue['type']}: {issue['matched_text']}")

        # Disclaimer Check
        disclaimer_check = result['checks_performed'].get('required_disclaimers', {})
        logger.info(f"  • Required Disclaimers: {'✅ PASS' if disclaimer_check.get('passed') else '❌ FAIL'}")
        logger.info(f"    Present: {disclaimer_check.get('present', [])}")
        logger.info(f"    Missing: {disclaimer_check.get('missing', [])}")

        # Risk Disclosure Check (if applicable)
        if 'risk_disclosure' in result['checks_performed']:
            risk_check = result['checks_performed']['risk_disclosure']
            logger.info(f"  • Risk Disclosure: {'✅ PASS' if risk_check.get('passed') else '⚠️  INSUFFICIENT'}")
            logger.info(f"    Disclosed: {len(risk_check.get('disclosed_risks', []))} risks")
            if not risk_check.get('passed'):
                logger.info(f"    Missing: {risk_check.get('missing_risks', [])[:3]}")

        # Issues Found
        if result.get('issues_found'):
            logger.info(f"\n⚠️  Issues Found ({len(result['issues_found'])}):")
            for issue in result['issues_found'][:3]:  # Show first 3
                logger.info(f"  • [{issue.get('severity', 'N/A')}] {issue.get('issue', issue.get('type', 'Unknown'))}")

        # Recommendations
        if result.get('recommendations'):
            logger.info(f"\n💡 Recommendations:")
            for rec in result['recommendations']:
                logger.info(f"  • {rec}")

        logger.info("\n" + "-"*80 + "\n")


async def test_disclaimer_generation_tool():
    """Test the disclaimer generation tool."""
    logger.info("\n" + "="*80)
    logger.info("TESTING DISCLAIMER GENERATION TOOL")
    logger.info("="*80 + "\n")

    from financial_advisor_agent.sub_agents.compliance_checker_agent.disclaimer_template_tool import disclaimer_template_tool

    test_scenarios = [
        {
            "content_type": "investment_advice",
            "description": "Investment advice disclaimers"
        },
        {
            "content_type": "tax_advice",
            "description": "Tax advice disclaimers"
        },
        {
            "content_type": "general_info",
            "description": "General information disclaimers"
        }
    ]

    for scenario in test_scenarios:
        logger.info(f"\n📋 Generating: {scenario['description']}")
        logger.info(f"Content Type: {scenario['content_type']}\n")

        result = disclaimer_template_tool.generate_disclaimers(
            content_type=scenario['content_type'],
            include_all_mandatory=True,
            format="full"
        )

        if result['success']:
            logger.info(f"✅ Generated {result['total_disclaimers']} disclaimers")
            logger.info(f"Mandatory: {result['mandatory_included']}")
            logger.info(f"Recommended available: {result['recommended_available']}")
            logger.info(f"\n📄 Formatted Output (first 500 chars):")
            output = result['formatted_output']
            logger.info(output[:500] + "..." if len(output) > 500 else output)
        else:
            logger.info(f"❌ Error: {result.get('error')}")

        logger.info("\n" + "-"*80)


async def test_agent_end_to_end():
    """Test the compliance checker agent end-to-end."""
    logger.info("\n" + "="*80)
    logger.info("TESTING COMPLIANCE CHECKER AGENT - END TO END")
    logger.info("="*80 + "\n")

    # Test with a sample response that needs compliance review
    test_response = """
    Based on current market conditions and your investment profile, I recommend
    allocating 60% to stock index funds and 40% to bonds. This balanced approach
    should provide steady growth with moderate risk.

    Historical data shows average annual returns of 8-10% for this allocation.
    """

    # Create a compliance review request
    review_request = f"""
    Please review the following financial advisory response for compliance:

    ---
    {test_response}
    ---

    Perform a comprehensive compliance check including:
    1. AI disclosure requirements
    2. Prohibited content detection
    3. Required disclaimers validation
    4. Risk disclosure adequacy
    5. Generate any missing disclaimers

    Provide your assessment with specific recommendations.
    """

    logger.info("📝 Sending compliance review request to agent...\n")
    logger.info(f"Review Request:\n{review_request}\n")
    logger.info("⏳ Processing...\n")

    try:
        # Use InMemoryRunner to run the agent
        from google.adk.runners import InMemoryRunner

        runner = InMemoryRunner(agent=compliance_checker_agent)
        result = await runner.run_debug(review_request, verbose=True)

        logger.info("="*80)
        logger.info("AGENT RESPONSE:")
        logger.info("="*80)

        # Extract the response text from the result
        if hasattr(result, 'text'):
            logger.info(result.text)
        elif isinstance(result, dict):
            logger.info(str(result))
        else:
            logger.info(str(result))

        logger.info("="*80 + "\n")

    except Exception as e:
        logger.error(f"❌ Error during agent test: {str(e)}")
        import traceback
        logger.error(traceback.format_exc())


async def main():
    """Run all tests."""
    logger.info("\n" + "="*80)
    logger.info("COMPLIANCE CHECKER AGENT - ISOLATION TEST SUITE")
    logger.info("="*80 + "\n")

    try:
        # Test 1: Direct tool testing - Compliance Validation
        await test_compliance_validation_tool()

        # Test 2: Direct tool testing - Disclaimer Generation
        await test_disclaimer_generation_tool()

        # Test 3: End-to-end agent testing
        await test_agent_end_to_end()

        logger.info("\n" + "="*80)
        logger.info("✅ ALL TESTS COMPLETED")
        logger.info("="*80 + "\n")

    except Exception as e:
        logger.error(f"\n❌ Test suite failed: {str(e)}")
        import traceback
        logger.error(traceback.format_exc())
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())
